---

- name: APT | Install sysvinit
  apt:
    pkg: "{{ dbs_sysvinit_packages }}"
    state: present
  register: sysv_installed

- block:

  - name: SHELL | Reboot machine
    shell: sleep 2 && shutdown -r now "Ansible updates triggered"
    async: 1
    poll: 0
    ignore_errors: true

  - name: WAIT_FOR_CONNECTION | Wait while rebooting...
    wait_for_connection:
      delay: 30
      timeout: 600

  - name: SETUP
    action: setup

  when: sysv_installed.changed

- name: APT | Purge systemd
  apt:
    pkg: systemd
    state: absent
    purge: yes

- name: COPY | Configure APT no extra packages
  copy:
    src: etc/apt/preferences.d/systemd
    dest: /etc/apt/preferences.d/systemd
