---

- name: APT | Install sysvinit
  ansible.builtin.apt:
    pkg: "{{ dbs_sysvinit_packages }}"
    state: present
  register: sysv_installed

- block:

    - name: REBOOT
      ansible.builtin.reboot:
        timeout: 3600

    - name: SETUP
      ansible.builtin.setup:

  when: sysv_installed.changed

- name: APT | Purge systemd
  ansible.builtin.apt:
    pkg: systemd
    state: absent
    purge: true

- name: COPY | Configure APT no extra packages
  ansible.builtin.copy:
    src: etc/apt/preferences.d/systemd
    dest: /etc/apt/preferences.d/systemd
    mode: 0644
    owner: root
    group: root
