---

- name: 'YUM - check on fire and forget task'
  async_status: jid={{ apt_install.ansible_job_id }}
  register: job_result
  until: apt_install.finished
  retries: 50

- name: APT | Install NTP daemon
  apt: pkg={{ dbs_ntp_pkg }} state=present
  when: dbs_set_ntp

- block:

  - name: APT | Install Intel Microcode if needed
    apt: >
      pkg=intel-microcode
      state=present
      default_release='{{ dbs_microcode_apt_distribution }}'
    when: ansible_processor[0].find('Intel') != -1

  - name: APT | Install AMD Microcode if needed
    apt: >
      pkg=amd64-microcode
      state=present
      default_release='{{ dbs_microcode_apt_distribution }}'
    when: ansible_processor[0].find('AMD')

  when: ansible_architecture == 'x86_64'
